### ISSUE TITLE
stability of this template for grid engine

### ISSUE THREAD

**Issue by jyhnnhyj** [Azure/cyclecloud-gridengine#2]
I've been trying cyclecloud and this template for grid-engine for a while now and I'm experiencing lots of issues

has any one used these templates in a serious workload?

my setup is really simple - I have an external nfs share and mount it on my grid engine nodes
have only one type of queue in my cluster / max cores can be several hundred 

for small number of jobs, all seems fine and the cluster works okay

but as soon as I submit a few hundred jobs, I encounter all sorts of strange issues
(and it's not related to my NFS, as I tried not accessing the NFS at all and still experienced similar issues)
to be specific, the issues are: jobs finish successfully, but for some of them, their status is still running in qstat (and this could continue for hours)
then hosts become unavailable when you run qhost (you see them with dashes in loads)
eventually all nodes become like that (but cyclecloud shows them healthy)
also on the cloud side, I have all those vms provisioned, up and running - I can log-in to them, but somehow they are no longer a part of my cluster, as they don't accept new jobs
sshing to those nodes, I can run various sge commands there, so they are still talking to the master - so in that sense still a part of the cluster...
not sure what's happening

the idea of cyclecloud is really nice, but my experience so far was really disappointing 

is there something obvious I'm doing wrong? any suggestions are really appreciated

**Comment by carogonzalezzapata** [comment]
Please try to update CycleCloud and then provide more details.

**Comment by carogonzalezzapata** [comment]
No more info. Closing the issue.
